// <auto-generated />
using System;
using GraduationProjectBackend.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraduationProjectBackend.DataAccess.Migrations
{
    [DbContext(typeof(MssqlDbContext))]
    [Migration("20230515120329_addFavorite")]
    partial class addFavorite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraduationProjectBackend.DataAccess.Models.Favorite.FavoriteFolder", b =>
                {
                    b.Property<int>("favoriteFolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("favoriteFolderId"));

                    b.Property<string>("favoriteFolderName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("favoriteFolderId");

                    b.ToTable("FavoriteFolder");
                });

            modelBuilder.Entity("GraduationProjectBackend.DataAccess.Models.Favorite.FavoriteFolderItem", b =>
                {
                    b.Property<int>("favoriteFolderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("favoriteFolderItemId"));

                    b.Property<int?>("favoriteFolderId")
                        .HasColumnType("int");

                    b.Property<int?>("favoriteItemId")
                        .HasColumnType("int");

                    b.HasKey("favoriteFolderItemId");

                    b.HasIndex("favoriteFolderId");

                    b.HasIndex("favoriteItemId");

                    b.ToTable("FavoriteFolderItem");
                });

            modelBuilder.Entity("GraduationProjectBackend.DataAccess.Models.Favorite.FavoriteItem", b =>
                {
                    b.Property<int>("favoriteItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("favoriteItemId"));

                    b.Property<string>("favoriteItemName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("favoriteItemId");

                    b.ToTable("FavoriteItem");
                });

            modelBuilder.Entity("GraduationProjectBackend.DataAccess.Models.Favorite.UserFavoriteFolder", b =>
                {
                    b.Property<int>("userFavoriteFolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userFavoriteFolderId"));

                    b.Property<int?>("favoriteFolderId")
                        .HasColumnType("int");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("userFavoriteFolderId");

                    b.HasIndex("favoriteFolderId");

                    b.HasIndex("userId");

                    b.ToTable("UserFavoriteFolder");
                });

            modelBuilder.Entity("GraduationProjectBackend.DataAccess.Models.Member.Role", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roleId"));

                    b.Property<string>("roleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("roleId");

                    b.HasIndex("userId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("GraduationProjectBackend.DataAccess.Models.Member.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("userId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("GraduationProjectBackend.DataAccess.Models.Member.UserRole", b =>
                {
                    b.Property<int>("userRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userRoleId"));

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("userRoleId");

                    b.HasIndex("roleId");

                    b.HasIndex("userId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("GraduationProjectBackend.DataAccess.Models.Favorite.FavoriteFolderItem", b =>
                {
                    b.HasOne("GraduationProjectBackend.DataAccess.Models.Favorite.FavoriteFolder", "favoriteFolder")
                        .WithMany()
                        .HasForeignKey("favoriteFolderId");

                    b.HasOne("GraduationProjectBackend.DataAccess.Models.Favorite.FavoriteItem", "favoriteItem")
                        .WithMany()
                        .HasForeignKey("favoriteItemId");

                    b.Navigation("favoriteFolder");

                    b.Navigation("favoriteItem");
                });

            modelBuilder.Entity("GraduationProjectBackend.DataAccess.Models.Favorite.UserFavoriteFolder", b =>
                {
                    b.HasOne("GraduationProjectBackend.DataAccess.Models.Favorite.FavoriteFolder", "favoriteFolder")
                        .WithMany()
                        .HasForeignKey("favoriteFolderId");

                    b.HasOne("GraduationProjectBackend.DataAccess.Models.Member.User", "user")
                        .WithMany()
                        .HasForeignKey("userId");

                    b.Navigation("favoriteFolder");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GraduationProjectBackend.DataAccess.Models.Member.Role", b =>
                {
                    b.HasOne("GraduationProjectBackend.DataAccess.Models.Member.User", null)
                        .WithMany("roles")
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("GraduationProjectBackend.DataAccess.Models.Member.UserRole", b =>
                {
                    b.HasOne("GraduationProjectBackend.DataAccess.Models.Member.Role", "role")
                        .WithMany()
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraduationProjectBackend.DataAccess.Models.Member.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GraduationProjectBackend.DataAccess.Models.Member.User", b =>
                {
                    b.Navigation("roles");
                });
#pragma warning restore 612, 618
        }
    }
}
